"""
Tip Rack Offset Test Protocol
Opentrons Flex - Simple calibration test

This protocol tests tip rack offsets by:
1. Picking up a tip from rack 1 (A1)
2. Dropping it in trash
3. Picking up a tip from rack 2 (A2)
4. Dropping it in trash

Use this to verify your tip rack calibration before running full protocols.

Deck Layout:
    ┌─────┬─────┬─────┬─────┐
    │ A1  │ A2  │ A3  │ A4  │  ← Tips 1, Tips 2, Trash, (empty)
    ├─────┼─────┼─────┼─────┤
    │ B1  │ B2  │ B3  │ B4  │  ← (empty)
    ├─────┼─────┼─────┼─────┤
    │ C1  │ C2  │ C3  │ C4  │  ← (empty)
    ├─────┼─────┼─────┼─────┤
    │ D1  │ D2  │ D3  │ D4  │  ← (empty)
    └─────┴─────┴─────┴─────┘

HOW TO GET OFFSET VALUES:
1. Load protocol in Opentrons App
2. Run "Labware Position Check" during setup
3. Record the X, Y, Z offset values shown for each tip rack
4. Enter those values as parameters before running
"""

from opentrons import protocol_api

metadata = {
    'protocolName': 'Tip Rack Offset Test',
    'author': 'Generated by Claude',
    'description': 'Simple test: pick up tip, drop, repeat - for calibration verification'
}

requirements = {
    'robotType': 'Flex',
    'apiLevel': '2.18'
}


# =============================================================================
# RUNTIME PARAMETERS
# =============================================================================

def add_parameters(parameters):
    """Define runtime parameters adjustable in the Opentrons app."""

    # Tip Rack 1 (A1) - Opentrons Flex 96 Tip Rack 1000 µL
    parameters.add_float(
        variable_name="tips1_offset_x",
        display_name="Tip Rack 1 X Offset",
        description="X offset for tip rack at A1 (mm)",
        default=0.0,
        minimum=-5.0,
        maximum=5.0,
        unit="mm"
    )
    parameters.add_float(
        variable_name="tips1_offset_y",
        display_name="Tip Rack 1 Y Offset",
        description="Y offset for tip rack at A1 (mm)",
        default=0.0,
        minimum=-5.0,
        maximum=5.0,
        unit="mm"
    )
    parameters.add_float(
        variable_name="tips1_offset_z",
        display_name="Tip Rack 1 Z Offset",
        description="Z offset for tip rack at A1 (mm)",
        default=0.0,
        minimum=-5.0,
        maximum=5.0,
        unit="mm"
    )

    # Tip Rack 2 (A2) - Opentrons Flex 96 Tip Rack 1000 µL
    parameters.add_float(
        variable_name="tips2_offset_x",
        display_name="Tip Rack 2 X Offset",
        description="X offset for tip rack at A2 (mm)",
        default=0.0,
        minimum=-5.0,
        maximum=5.0,
        unit="mm"
    )
    parameters.add_float(
        variable_name="tips2_offset_y",
        display_name="Tip Rack 2 Y Offset",
        description="Y offset for tip rack at A2 (mm)",
        default=0.0,
        minimum=-5.0,
        maximum=5.0,
        unit="mm"
    )
    parameters.add_float(
        variable_name="tips2_offset_z",
        display_name="Tip Rack 2 Z Offset",
        description="Z offset for tip rack at A2 (mm)",
        default=0.0,
        minimum=-5.0,
        maximum=5.0,
        unit="mm"
    )


def run(protocol: protocol_api.ProtocolContext):

    # =========================================================================
    # GET RUNTIME PARAMETERS
    # =========================================================================

    tips1_offset = {
        'x': protocol.params.tips1_offset_x,
        'y': protocol.params.tips1_offset_y,
        'z': protocol.params.tips1_offset_z
    }
    tips2_offset = {
        'x': protocol.params.tips2_offset_x,
        'y': protocol.params.tips2_offset_y,
        'z': protocol.params.tips2_offset_z
    }

    # =========================================================================
    # LABWARE SETUP
    # =========================================================================

    tips_1000_1 = protocol.load_labware('opentrons_flex_96_tiprack_1000ul', 'A1')
    tips_1000_2 = protocol.load_labware('opentrons_flex_96_tiprack_1000ul', 'A2')

    trash = protocol.load_trash_bin('A3')

    # =========================================================================
    # APPLY LABWARE OFFSETS
    # =========================================================================

    protocol.comment('=' * 60)
    protocol.comment('APPLYING LABWARE OFFSETS')
    protocol.comment('=' * 60)

    tips_1000_1.set_offset(
        x=tips1_offset['x'],
        y=tips1_offset['y'],
        z=tips1_offset['z']
    )
    protocol.comment(f"Tip Rack 1 (A1): x={tips1_offset['x']}, y={tips1_offset['y']}, z={tips1_offset['z']} mm")

    tips_1000_2.set_offset(
        x=tips2_offset['x'],
        y=tips2_offset['y'],
        z=tips2_offset['z']
    )
    protocol.comment(f"Tip Rack 2 (A2): x={tips2_offset['x']}, y={tips2_offset['y']}, z={tips2_offset['z']} mm")

    # =========================================================================
    # PIPETTE SETUP
    # =========================================================================

    p1000 = protocol.load_instrument(
        'flex_1channel_1000',
        'right',
        tip_racks=[tips_1000_1, tips_1000_2]
    )

    # =========================================================================
    # TEST SEQUENCE
    # =========================================================================

    protocol.comment('=' * 60)
    protocol.comment('TIP RACK OFFSET TEST')
    protocol.comment('=' * 60)

    # Test 1: Pick up from rack 1, drop in trash
    protocol.comment('Test 1: Picking up tip from Rack 1 (A1)')
    p1000.pick_up_tip(tips_1000_1['A1'])
    protocol.comment('Dropping tip in trash')
    p1000.drop_tip()

    # Test 2: Pick up from rack 2, drop in trash
    protocol.comment('Test 2: Picking up tip from Rack 2 (A2)')
    p1000.pick_up_tip(tips_1000_2['A1'])
    protocol.comment('Dropping tip in trash')
    p1000.drop_tip()

    protocol.comment('=' * 60)
    protocol.comment('TEST COMPLETE')
    protocol.comment('If tips were picked up cleanly, offsets are good!')
    protocol.comment('=' * 60)
