"""
Doxorubicin Cardiotoxicity Dose-Response Protocol
Opentrons Flex - 24hr Hackathon (Backup/Validation Experiment)

This protocol performs serial dilution of doxorubicin and treats pre-plated
cardiac organoids for cardiotoxicity dose-response curve.

Concentrations: 0 (vehicle), 0.1, 0.3, 1, 3, 10 µM doxorubicin (half-log steps)

Plate Layout (cell_plate):
- Row A, Col 1-4: Vehicle control (n=4)
- Row A, Col 5-8: 0.1 µM Dox (n=4)
- Row A, Col 9-12: 0.3 µM Dox (n=4)
- Row B, Col 1-4: 1 µM Dox (n=4)
- Row B, Col 5-8: 3 µM Dox (n=4)
- Row B, Col 9-12: 10 µM Dox (n=4)
- Row G-H, Col 1-4: Blanks (no cells)

Deck Layout:
- A1: 200 µL tip rack #1
- A2: 200 µL tip rack #2
- B1: 12-well reservoir
- C1: Dilution plate (for serial dilution prep)
- D1: Cell plate (pre-plated cardiac organoids)
"""

from opentrons import protocol_api

metadata = {
    'protocolName': 'Doxorubicin Cardiotoxicity Dose-Response',
    'author': 'Generated by Claude for Hackathon',
    'description': 'Half-log serial dilution of doxorubicin on cardiac organoids',
}

requirements = {
    'robotType': 'Flex',
    'apiLevel': '2.16'
}

def run(protocol: protocol_api.ProtocolContext):
    
    # === LABWARE SETUP ===
    tips_200_1 = protocol.load_labware('opentrons_flex_96_tiprack_200ul', 'A1')
    tips_200_2 = protocol.load_labware('opentrons_flex_96_tiprack_200ul', 'A2')
    reservoir = protocol.load_labware('nest_12_reservoir_15ml', 'B1')
    dilution_plate = protocol.load_labware('corning_96_wellplate_360ul_flat', 'C1')
    cell_plate = protocol.load_labware('corning_96_wellplate_360ul_flat', 'D1')
    
    # === PIPETTE SETUP ===
    p8_200 = protocol.load_instrument(
        'flex_8channel_1000',
        'right',
        tip_racks=[tips_200_1, tips_200_2]
    )
    
    # Gentle handling for organoids
    p8_200.flow_rate.aspirate = 100
    p8_200.flow_rate.dispense = 150
    
    # === REAGENT LOCATIONS ===
    media = reservoir.wells_by_name()['A1']           # Diluent
    dox_30um = reservoir.wells_by_name()['A2']        # 30 µM Dox stock (3x highest conc)
    fluo4 = reservoir.wells_by_name()['A12']          # Fluo-4 AM working solution
    ctg = reservoir.wells_by_name()['A11']            # CellTiter-Glo (optional)
    
    # === SERIAL DILUTION PARAMETERS ===
    # Target concentrations: 10, 3, 1, 0.3, 0.1 µM (half-log = 3.16x dilution)
    # Starting from 30 µM stock to get 10 µM as first dilution
    
    total_vol = 250  # µL total volume per well in dilution plate
    dilution_factor = 3.16  # Half-log
    transfer_vol = int(total_vol / dilution_factor)  # ~79 µL
    diluent_vol = total_vol - transfer_vol  # ~171 µL
    
    protocol.comment('='*50)
    protocol.comment('SERIAL DILUTION PREPARATION')
    protocol.comment('='*50)
    
    # Step 1: Add diluent to columns 2-5 of dilution plate (for 3, 1, 0.3, 0.1 µM)
    protocol.comment('Step 1: Adding diluent to dilution plate columns 2-5')
    p8_200.pick_up_tip()
    for col_idx in range(1, 5):  # Columns 2-5
        p8_200.aspirate(diluent_vol, media)
        p8_200.dispense(diluent_vol, dilution_plate.columns()[col_idx][0])
    p8_200.drop_tip()
    
    # Step 2: Add 30 µM stock to column 1 (will give 10 µM when diluted 1:3 in cell media)
    protocol.comment('Step 2: Adding 30 µM Dox stock to column 1')
    p8_200.pick_up_tip()
    p8_200.aspirate(total_vol, dox_30um)
    p8_200.dispense(total_vol, dilution_plate.columns()[0][0])
    p8_200.mix(3, 150)
    p8_200.drop_tip()
    
    # Step 3: Perform serial dilution
    protocol.comment('Step 3: Performing serial dilutions')
    for i in range(4):  # 4 dilution steps (10→3→1→0.3→0.1)
        p8_200.pick_up_tip()
        p8_200.aspirate(transfer_vol, dilution_plate.columns()[i][0])
        p8_200.dispense(transfer_vol, dilution_plate.columns()[i+1][0])
        p8_200.mix(3, 150)  # Mix well
        p8_200.drop_tip()
    
    protocol.comment('Serial dilution complete.')
    protocol.comment('Dilution plate layout:')
    protocol.comment('  Col 1: 30 µM (will be 10 µM in cells)')
    protocol.comment('  Col 2: 9.5 µM (will be 3 µM in cells)')
    protocol.comment('  Col 3: 3 µM (will be 1 µM in cells)')
    protocol.comment('  Col 4: 0.95 µM (will be 0.3 µM in cells)')
    protocol.comment('  Col 5: 0.3 µM (will be 0.1 µM in cells)')
    
    # === TREATMENT ADDITION TO CELLS ===
    
    protocol.comment('='*50)
    protocol.comment('TREATMENT ADDITION TO CELL PLATE')
    protocol.comment('='*50)
    
    treatment_vol = 100  # µL per well
    
    # Define well groups on cell plate
    # Row A: Vehicle, 0.1, 0.3 µM
    # Row B: 1, 3, 10 µM
    
    well_groups = {
        'vehicle': ['A1', 'A2', 'A3', 'A4'],      # Media only
        'dox_0.1': ['A5', 'A6', 'A7', 'A8'],      # 0.1 µM (col 5)
        'dox_0.3': ['A9', 'A10', 'A11', 'A12'],   # 0.3 µM (col 4)
        'dox_1': ['B1', 'B2', 'B3', 'B4'],        # 1 µM (col 3)
        'dox_3': ['B5', 'B6', 'B7', 'B8'],        # 3 µM (col 2)
        'dox_10': ['B9', 'B10', 'B11', 'B12'],    # 10 µM (col 1)
    }
    
    # Vehicle control
    protocol.comment('Adding vehicle control (media only)')
    p8_200.pick_up_tip()
    for well in well_groups['vehicle']:
        p8_200.aspirate(treatment_vol, media)
        p8_200.dispense(treatment_vol, cell_plate.wells_by_name()[well])
        p8_200.touch_tip()
    p8_200.drop_tip()
    
    # 0.1 µM (from dilution plate column 5)
    protocol.comment('Adding 0.1 µM doxorubicin')
    p8_200.pick_up_tip()
    for well in well_groups['dox_0.1']:
        p8_200.aspirate(treatment_vol, dilution_plate.columns()[4][0])
        p8_200.dispense(treatment_vol, cell_plate.wells_by_name()[well])
        p8_200.touch_tip()
    p8_200.drop_tip()
    
    # 0.3 µM (from dilution plate column 4)
    protocol.comment('Adding 0.3 µM doxorubicin')
    p8_200.pick_up_tip()
    for well in well_groups['dox_0.3']:
        p8_200.aspirate(treatment_vol, dilution_plate.columns()[3][0])
        p8_200.dispense(treatment_vol, cell_plate.wells_by_name()[well])
        p8_200.touch_tip()
    p8_200.drop_tip()
    
    # 1 µM (from dilution plate column 3)
    protocol.comment('Adding 1 µM doxorubicin')
    p8_200.pick_up_tip()
    for well in well_groups['dox_1']:
        p8_200.aspirate(treatment_vol, dilution_plate.columns()[2][0])
        p8_200.dispense(treatment_vol, cell_plate.wells_by_name()[well])
        p8_200.touch_tip()
    p8_200.drop_tip()
    
    # 3 µM (from dilution plate column 2)
    protocol.comment('Adding 3 µM doxorubicin')
    p8_200.pick_up_tip()
    for well in well_groups['dox_3']:
        p8_200.aspirate(treatment_vol, dilution_plate.columns()[1][0])
        p8_200.dispense(treatment_vol, cell_plate.wells_by_name()[well])
        p8_200.touch_tip()
    p8_200.drop_tip()
    
    # 10 µM (from dilution plate column 1)
    protocol.comment('Adding 10 µM doxorubicin')
    p8_200.pick_up_tip()
    for well in well_groups['dox_10']:
        p8_200.aspirate(treatment_vol, dilution_plate.columns()[0][0])
        p8_200.dispense(treatment_vol, cell_plate.wells_by_name()[well])
        p8_200.touch_tip()
    p8_200.drop_tip()
    
    protocol.comment('='*50)
    protocol.comment('TREATMENT COMPLETE')
    protocol.comment('Incubate plate for 24 hours at 37°C, 5% CO2')
    protocol.comment('='*50)
    
    protocol.pause('PAUSE: Incubate 24 hours. Press RESUME for Fluo-4 addition.')
    
    # === FLUO-4 ADDITION ===
    
    protocol.comment('='*50)
    protocol.comment('FLUO-4 AM ADDITION FOR CALCIUM IMAGING')
    protocol.comment('='*50)
    
    all_wells = []
    for group in well_groups.values():
        all_wells.extend(group)
    
    fluo4_vol = 50  # µL
    
    for well in all_wells:
        p8_200.pick_up_tip()
        p8_200.aspirate(fluo4_vol, fluo4)
        p8_200.dispense(fluo4_vol, cell_plate.wells_by_name()[well])
        p8_200.touch_tip()
        p8_200.drop_tip()
    
    protocol.comment('='*50)
    protocol.comment('PROTOCOL COMPLETE')
    protocol.comment('Incubate 30 min at 37°C (protected from light)')
    protocol.comment('Read on plate reader: Ex 494 nm, Em 516 nm')
    protocol.comment('Optional: Add CellTiter-Glo for viability')
    protocol.comment('='*50)


# === REAGENT PREPARATION GUIDE ===
"""
DOXORUBICIN DOSE-RESPONSE SETUP

1. Media (Diluent) - 15 mL in reservoir A1
   - RPMI 1640 + B27 or your cardiac maintenance media

2. Doxorubicin 30 µM Stock - 3 mL in reservoir A2
   - From 10 mM DMSO stock: dilute 9 µL in 3 mL media
   - Filter sterilize if needed
   - Final DMSO: 0.3% (acceptable for cells)
   
   NOTE: 30 µM in dilution plate will give 10 µM when diluted 1:3 
   into cell culture wells (100 µL treatment into ~200 µL existing media)

3. Fluo-4 AM Working Solution - 5 mL in reservoir A12
   - From 1 mM DMSO stock: 10 µL in 5 mL imaging buffer
   - Add 0.02% Pluronic F-127
   - Prepare fresh, protect from light

4. CellTiter-Glo (optional) - 5 mL in reservoir A11
   - Thaw at RT 30 min before use
   - Add equal volume to well content

EXPECTED RESULTS:
- IC50 typically 0.5-3 µM for iPSC-CMs
- Dose-dependent decrease in:
  - Calcium transient amplitude
  - Beating rate
  - Cell viability
- Higher concentrations (10 µM) should show ~50-80% reduction

POSITIVE CONTROL VALIDATION:
- If you get no dose-response, check:
  - Dox stock integrity (should be red/orange)
  - Cell density (need enough cells to see effect)
  - Incubation time (may need longer for low doses)
"""