"""
Gripper Tip Rack Demo Protocol
Opentrons Flex - Gripper Choreography

This protocol demonstrates the gripper by moving tip racks around the deck.
No reagents or plates needed - just tip racks!

Sequence:
1. Start: Rack 1 at A1, Rack 2 at A2
2. Gripper moves Rack 1 from A1 → B1
3. Gripper moves Rack 2 from A2 → A1
4. Gripper moves Rack 1 from B1 → A2
5. End: Racks have swapped positions

Deck Layout:
    ┌─────┬─────┬─────┬─────┐
    │ A1  │ A2  │ A3  │ A4  │  ← Tips 1, Tips 2, Trash, (empty)
    ├─────┼─────┼─────┼─────┤
    │ B1  │ B2  │ B3  │ B4  │  ← (staging), (empty), (empty), (empty)
    ├─────┼─────┼─────┼─────┤
    │ C1  │ C2  │ C3  │ C4  │  ← (empty)
    ├─────┼─────┼─────┼─────┤
    │ D1  │ D2  │ D3  │ D4  │  ← (empty)
    └─────┴─────┴─────┴─────┘
"""

from opentrons import protocol_api

metadata = {
    'protocolName': 'Gripper Tip Rack Demo',
    'author': 'Generated by Claude',
    'description': 'Demonstrates gripper by moving tip racks around the deck'
}

requirements = {
    'robotType': 'Flex',
    'apiLevel': '2.18'
}


# =============================================================================
# RUNTIME PARAMETERS
# =============================================================================

def add_parameters(parameters):
    """Define runtime parameters adjustable in the Opentrons app."""

    # Tip Rack 1 (starts at A1)
    parameters.add_float(
        variable_name="tips1_offset_x",
        display_name="Tip Rack 1 X Offset",
        description="X offset for tip rack starting at A1 (mm)",
        default=0.0,
        minimum=-5.0,
        maximum=5.0,
        unit="mm"
    )
    parameters.add_float(
        variable_name="tips1_offset_y",
        display_name="Tip Rack 1 Y Offset",
        description="Y offset for tip rack starting at A1 (mm)",
        default=0.0,
        minimum=-5.0,
        maximum=5.0,
        unit="mm"
    )
    parameters.add_float(
        variable_name="tips1_offset_z",
        display_name="Tip Rack 1 Z Offset",
        description="Z offset for tip rack starting at A1 (mm)",
        default=0.0,
        minimum=-5.0,
        maximum=5.0,
        unit="mm"
    )

    # Tip Rack 2 (starts at A2)
    parameters.add_float(
        variable_name="tips2_offset_x",
        display_name="Tip Rack 2 X Offset",
        description="X offset for tip rack starting at A2 (mm)",
        default=0.0,
        minimum=-5.0,
        maximum=5.0,
        unit="mm"
    )
    parameters.add_float(
        variable_name="tips2_offset_y",
        display_name="Tip Rack 2 Y Offset",
        description="Y offset for tip rack starting at A2 (mm)",
        default=0.0,
        minimum=-5.0,
        maximum=5.0,
        unit="mm"
    )
    parameters.add_float(
        variable_name="tips2_offset_z",
        display_name="Tip Rack 2 Z Offset",
        description="Z offset for tip rack starting at A2 (mm)",
        default=0.0,
        minimum=-5.0,
        maximum=5.0,
        unit="mm"
    )

    # Demo options
    parameters.add_int(
        variable_name="num_cycles",
        display_name="Number of Cycles",
        description="How many times to run the swap sequence",
        default=1,
        minimum=1,
        maximum=5,
        unit="cycles"
    )


def run(protocol: protocol_api.ProtocolContext):

    # =========================================================================
    # GET RUNTIME PARAMETERS
    # =========================================================================

    tips1_offset = {
        'x': protocol.params.tips1_offset_x,
        'y': protocol.params.tips1_offset_y,
        'z': protocol.params.tips1_offset_z
    }
    tips2_offset = {
        'x': protocol.params.tips2_offset_x,
        'y': protocol.params.tips2_offset_y,
        'z': protocol.params.tips2_offset_z
    }
    num_cycles = protocol.params.num_cycles

    # =========================================================================
    # LABWARE SETUP
    # =========================================================================

    tips_1 = protocol.load_labware('opentrons_flex_96_tiprack_1000ul', 'A1')
    tips_2 = protocol.load_labware('opentrons_flex_96_tiprack_1000ul', 'A2')

    trash = protocol.load_trash_bin('A3')

    # =========================================================================
    # APPLY LABWARE OFFSETS
    # =========================================================================

    protocol.comment('=' * 60)
    protocol.comment('APPLYING LABWARE OFFSETS')
    protocol.comment('=' * 60)

    tips_1.set_offset(
        x=tips1_offset['x'],
        y=tips1_offset['y'],
        z=tips1_offset['z']
    )
    protocol.comment(f"Tip Rack 1: x={tips1_offset['x']}, y={tips1_offset['y']}, z={tips1_offset['z']} mm")

    tips_2.set_offset(
        x=tips2_offset['x'],
        y=tips2_offset['y'],
        z=tips2_offset['z']
    )
    protocol.comment(f"Tip Rack 2: x={tips2_offset['x']}, y={tips2_offset['y']}, z={tips2_offset['z']} mm")

    # =========================================================================
    # GRIPPER DEMO SEQUENCE
    # =========================================================================

    protocol.comment('=' * 60)
    protocol.comment('GRIPPER TIP RACK DEMO')
    protocol.comment(f'Running {num_cycles} cycle(s)')
    protocol.comment('=' * 60)

    for cycle in range(num_cycles):
        protocol.comment(f'--- Cycle {cycle + 1} of {num_cycles} ---')

        # Step 1: Move Rack 1 from A1 to B1 (staging)
        protocol.comment('Step 1: Moving Tip Rack 1 from A1 → B1')
        protocol.move_labware(
            labware=tips_1,
            new_location='B1',
            use_gripper=True
        )

        # Step 2: Move Rack 2 from A2 to A1
        protocol.comment('Step 2: Moving Tip Rack 2 from A2 → A1')
        protocol.move_labware(
            labware=tips_2,
            new_location='A1',
            use_gripper=True
        )

        # Step 3: Move Rack 1 from B1 to A2
        protocol.comment('Step 3: Moving Tip Rack 1 from B1 → A2')
        protocol.move_labware(
            labware=tips_1,
            new_location='A2',
            use_gripper=True
        )

        protocol.comment(f'Cycle {cycle + 1} complete - racks have swapped positions!')

        # If doing multiple cycles, swap back for the next cycle
        if cycle < num_cycles - 1:
            protocol.comment('Swapping back for next cycle...')

            protocol.move_labware(
                labware=tips_2,
                new_location='B1',
                use_gripper=True
            )
            protocol.move_labware(
                labware=tips_1,
                new_location='A1',
                use_gripper=True
            )
            protocol.move_labware(
                labware=tips_2,
                new_location='A2',
                use_gripper=True
            )

    protocol.comment('=' * 60)
    protocol.comment('GRIPPER DEMO COMPLETE!')
    protocol.comment('=' * 60)
    protocol.comment('Final positions:')
    protocol.comment('  - Original Rack 1 is now at A2')
    protocol.comment('  - Original Rack 2 is now at A1')
    protocol.comment('=' * 60)
