"""
Heart Organoid Inflammatory Challenge Protocol
Opentrons Flex - 24hr Hackathon

Generated from Hypothesis Skill Output:
{
  "selected_hypothesis": {
    "id": "hyp_1",
    "statement": "Acute inflammatory stimulation (TNF-α or IL-1β) of cardiac organoids
                  will induce measurable changes in calcium transient dynamics within 24 hours",
    "experiment_type": "dose_response"
  },
  "experimental_design": {
    "groups": [
      {"name": "vehicle_control", "treatment": "media only", "n": 12},
      {"name": "TNF_10", "treatment": "TNF-α 10 ng/mL", "n": 12},
      {"name": "TNF_50", "treatment": "TNF-α 50 ng/mL", "n": 12},
      {"name": "IL1B_10", "treatment": "IL-1β 10 ng/mL", "n": 12},
      {"name": "IL1B_50", "treatment": "IL-1β 50 ng/mL", "n": 12},
      {"name": "cond_media", "treatment": "conditioned media", "n": 12}
    ],
    "plate_format": "96-well",
    "timeline_hours": 24,
    "readouts": [
      {"type": "plate_reader", "target": "calcium", "method": "Fluo-4 AM"}
    ]
  }
}

Deck Layout:
    ┌─────┬─────┬─────┬─────┐
    │ A1  │ A2  │ A3  │ A4  │  ← Tips, Tips, Trash, Staging
    ├─────┼─────┼─────┼─────┤
    │ B1  │ B2  │ B3  │ B4  │  ← Reservoir, (empty), (empty), Staging
    ├─────┼─────┼─────┼─────┤
    │ C1  │ C2  │ C3  │ C4  │  ← (empty), (empty), (empty), Staging
    ├─────┼─────┼─────┼─────┤
    │ D1  │ D2  │ D3  │ D4  │  ← Cell Plate, (empty), (empty), Staging
    └─────┴─────┴─────┴─────┘

Plate Layout (cell_plate D1):
|   | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 |
|---|---|---|---|---|---|---|---|---|---|----|----|-----|
| A | V | V | V | V | V | V | T10| T10| T10| T10| T10| T10|
| B | V | V | V | V | V | V | T10| T10| T10| T10| T10| T10|
| C | T50| T50| T50| T50| T50| T50| I10| I10| I10| I10| I10| I10|
| D | T50| T50| T50| T50| T50| T50| I10| I10| I10| I10| I10| I10|
| E | I50| I50| I50| I50| I50| I50| CM | CM | CM | CM | CM | CM |
| F | I50| I50| I50| I50| I50| I50| CM | CM | CM | CM | CM | CM |
| G | BL | BL | BL | BL | - | - | - | - | - | - | - | - |
| H | BL | BL | BL | BL | - | - | - | - | - | - | - | - |

Legend:
- V = Vehicle Control (media only)
- T10 = TNF-α 10 ng/mL
- T50 = TNF-α 50 ng/mL
- I10 = IL-1β 10 ng/mL
- I50 = IL-1β 50 ng/mL
- CM = Conditioned Media (or additional control)
- BL = Blank (no cells, for background subtraction)

ENHANCEMENTS IN THIS VERSION:
1. Runtime Parameters - adjust volumes and flow rates from the app
2. Liquid Definitions - visual deck setup in the app
"""

from opentrons import protocol_api

metadata = {
    'protocolName': 'Heart Organoid Inflammatory Challenge v4',
    'author': 'Generated by Claude - WITH PARAMETERS & LIQUIDS',
    'description': 'TNF-α/IL-1β dose-response on cardiac organoids with Fluo-4 calcium readout'
}

requirements = {
    'robotType': 'Flex',
    'apiLevel': '2.18'
}


# =============================================================================
# RUNTIME PARAMETERS
# =============================================================================

def add_parameters(parameters):
    """Define runtime parameters adjustable in the Opentrons app."""

    # Volume parameters
    parameters.add_int(
        variable_name="treatment_volume",
        display_name="Treatment Volume (µL)",
        description="Volume of treatment solution to add per well",
        default=100,
        minimum=50,
        maximum=200,
        unit="µL"
    )

    parameters.add_int(
        variable_name="fluo4_volume",
        display_name="Fluo-4 Volume (µL)",
        description="Volume of Fluo-4 AM solution to add per well",
        default=50,
        minimum=25,
        maximum=100,
        unit="µL"
    )

    # Flow rate parameters
    parameters.add_int(
        variable_name="aspirate_rate",
        display_name="Aspirate Flow Rate",
        description="Slower rates are gentler on organoids (µL/s)",
        default=100,
        minimum=50,
        maximum=300,
        unit="µL/s"
    )

    parameters.add_int(
        variable_name="dispense_rate",
        display_name="Dispense Flow Rate",
        description="Slower rates are gentler on organoids (µL/s)",
        default=150,
        minimum=50,
        maximum=300,
        unit="µL/s"
    )

    # Protocol options
    parameters.add_bool(
        variable_name="skip_fluo4",
        display_name="Skip Fluo-4 Addition",
        description="Set to True if adding Fluo-4 manually later",
        default=False
    )

    parameters.add_bool(
        variable_name="include_blanks",
        display_name="Include Blank Wells",
        description="Add media to blank wells for background measurement",
        default=False
    )


def run(protocol: protocol_api.ProtocolContext):

    # =========================================================================
    # GET RUNTIME PARAMETERS
    # =========================================================================

    treatment_vol = protocol.params.treatment_volume
    fluo4_vol = protocol.params.fluo4_volume
    aspirate_rate = protocol.params.aspirate_rate
    dispense_rate = protocol.params.dispense_rate
    skip_fluo4 = protocol.params.skip_fluo4
    include_blanks = protocol.params.include_blanks

    # =========================================================================
    # LABWARE SETUP
    # =========================================================================

    # Tip racks (need 2 for all transfers + Fluo-4 addition)
    tips_1000_1 = protocol.load_labware('opentrons_flex_96_tiprack_1000ul', 'A1')
    tips_1000_2 = protocol.load_labware('opentrons_flex_96_tiprack_1000ul', 'A2')

    # Trash bin (REQUIRED for Flex)
    trash = protocol.load_trash_bin('A3')

    # Reservoir for reagents (12-well, 15 mL per well)
    reservoir = protocol.load_labware('nest_12_reservoir_15ml', 'B1')

    # Cell plate (pre-plated with cardiac organoids)
    cell_plate = protocol.load_labware('corning_96_wellplate_360ul_flat', 'D1')

    # =========================================================================
    # LIQUID DEFINITIONS
    # =========================================================================

    # Define liquids with colors for app visualization
    media_liquid = protocol.define_liquid(
        name="Media (Vehicle)",
        description="RPMI 1640 + B27 cardiac maintenance media",
        display_color="#90EE90"  # Light green
    )

    tnf_10_liquid = protocol.define_liquid(
        name="TNF-α 10 ng/mL",
        description="TNF-alpha at 10 ng/mL in media",
        display_color="#FF6B6B"  # Red
    )

    tnf_50_liquid = protocol.define_liquid(
        name="TNF-α 50 ng/mL",
        description="TNF-alpha at 50 ng/mL in media",
        display_color="#CC0000"  # Dark red
    )

    il1b_10_liquid = protocol.define_liquid(
        name="IL-1β 10 ng/mL",
        description="IL-1beta at 10 ng/mL in media",
        display_color="#6BB3FF"  # Light blue
    )

    il1b_50_liquid = protocol.define_liquid(
        name="IL-1β 50 ng/mL",
        description="IL-1beta at 50 ng/mL in media",
        display_color="#0066CC"  # Dark blue
    )

    cond_media_liquid = protocol.define_liquid(
        name="Conditioned Media",
        description="Macrophage conditioned media",
        display_color="#FFB347"  # Orange
    )

    fluo4_liquid = protocol.define_liquid(
        name="Fluo-4 AM",
        description="Fluo-4 AM 2 µM calcium indicator dye",
        display_color="#98FB98"  # Pale green (fluorescent)
    )

    # =========================================================================
    # LOAD LIQUIDS INTO RESERVOIR
    # =========================================================================

    # Load liquids with starting volumes (in µL)
    reservoir['A1'].load_liquid(liquid=media_liquid, volume=10000)      # 10 mL
    reservoir['A2'].load_liquid(liquid=tnf_10_liquid, volume=3000)      # 3 mL
    reservoir['A3'].load_liquid(liquid=tnf_50_liquid, volume=3000)      # 3 mL
    reservoir['A4'].load_liquid(liquid=il1b_10_liquid, volume=3000)     # 3 mL
    reservoir['A5'].load_liquid(liquid=il1b_50_liquid, volume=3000)     # 3 mL
    reservoir['A6'].load_liquid(liquid=cond_media_liquid, volume=3000)  # 3 mL
    reservoir['A12'].load_liquid(liquid=fluo4_liquid, volume=8000)      # 8 mL

    # =========================================================================
    # PIPETTE SETUP
    # =========================================================================

    # Using single-channel (plate layout has mixed treatments in same columns)
    p1000 = protocol.load_instrument(
        'flex_1channel_1000',
        'right',
        tip_racks=[tips_1000_1, tips_1000_2]
    )

    # Set flow rates from parameters
    p1000.flow_rate.aspirate = aspirate_rate
    p1000.flow_rate.dispense = dispense_rate

    # =========================================================================
    # REAGENT LOCATIONS
    # =========================================================================

    media = reservoir['A1']
    tnf_10 = reservoir['A2']
    tnf_50 = reservoir['A3']
    il1b_10 = reservoir['A4']
    il1b_50 = reservoir['A5']
    cond_media = reservoir['A6']
    fluo4 = reservoir['A12']

    # =========================================================================
    # WELL DEFINITIONS
    # =========================================================================

    # Vehicle: Rows A-B, Cols 1-6 (n=12)
    vehicle_wells = [f'{row}{col}' for row in ['A', 'B'] for col in range(1, 7)]

    # TNF-α 10 ng/mL: Rows A-B, Cols 7-12 (n=12)
    tnf10_wells = [f'{row}{col}' for row in ['A', 'B'] for col in range(7, 13)]

    # TNF-α 50 ng/mL: Rows C-D, Cols 1-6 (n=12)
    tnf50_wells = [f'{row}{col}' for row in ['C', 'D'] for col in range(1, 7)]

    # IL-1β 10 ng/mL: Rows C-D, Cols 7-12 (n=12)
    il1b10_wells = [f'{row}{col}' for row in ['C', 'D'] for col in range(7, 13)]

    # IL-1β 50 ng/mL: Rows E-F, Cols 1-6 (n=12)
    il1b50_wells = [f'{row}{col}' for row in ['E', 'F'] for col in range(1, 7)]

    # Conditioned media: Rows E-F, Cols 7-12 (n=12)
    cm_wells = [f'{row}{col}' for row in ['E', 'F'] for col in range(7, 13)]

    # All treatment wells (for Fluo-4 addition)
    all_treatment_wells = (vehicle_wells + tnf10_wells + tnf50_wells +
                          il1b10_wells + il1b50_wells + cm_wells)

    # Blank wells for background (no cells)
    blank_wells = [f'{row}{col}' for row in ['G', 'H'] for col in range(1, 5)]

    # =========================================================================
    # HELPER FUNCTION
    # =========================================================================

    def add_treatment(source, wells, volume, description):
        """
        Add treatment to specified wells.
        Uses new tip for each treatment group to prevent cross-contamination.
        """
        protocol.comment(f'Adding {description}')
        p1000.pick_up_tip()

        for well_name in wells:
            p1000.aspirate(volume, source.bottom(z=2))
            p1000.dispense(volume, cell_plate.wells_by_name()[well_name].bottom(z=5))
            p1000.touch_tip()

        p1000.blow_out(source.top())
        p1000.drop_tip()

    # =========================================================================
    # PROTOCOL STEPS - TREATMENT ADDITION
    # =========================================================================

    protocol.comment('=' * 60)
    protocol.comment('PHASE 1: INFLAMMATORY TREATMENT ADDITION')
    protocol.comment(f'Treatment volume: {treatment_vol} µL per well')
    protocol.comment(f'Flow rates: aspirate={aspirate_rate}, dispense={dispense_rate} µL/s')
    protocol.comment('=' * 60)

    # Step 1: Vehicle control
    add_treatment(media, vehicle_wells, treatment_vol,
                  'Vehicle control (media) - Rows A-B, Cols 1-6')

    # Step 2: TNF-α 10 ng/mL
    add_treatment(tnf_10, tnf10_wells, treatment_vol,
                  'TNF-α 10 ng/mL - Rows A-B, Cols 7-12')

    # Step 3: TNF-α 50 ng/mL
    add_treatment(tnf_50, tnf50_wells, treatment_vol,
                  'TNF-α 50 ng/mL - Rows C-D, Cols 1-6')

    # Step 4: IL-1β 10 ng/mL
    add_treatment(il1b_10, il1b10_wells, treatment_vol,
                  'IL-1β 10 ng/mL - Rows C-D, Cols 7-12')

    # Step 5: IL-1β 50 ng/mL
    add_treatment(il1b_50, il1b50_wells, treatment_vol,
                  'IL-1β 50 ng/mL - Rows E-F, Cols 1-6')

    # Step 6: Conditioned media
    add_treatment(cond_media, cm_wells, treatment_vol,
                  'Conditioned media - Rows E-F, Cols 7-12')

    # Optional: Add media to blank wells
    if include_blanks:
        add_treatment(media, blank_wells, treatment_vol,
                      'Media to blank wells - Rows G-H, Cols 1-4')

    protocol.comment('=' * 60)
    protocol.comment('TREATMENT ADDITION COMPLETE')
    protocol.comment(f'Total wells treated: {len(all_treatment_wells)}')
    protocol.comment('Transfer to incubator: 37°C, 5% CO2, 24 hours')
    protocol.comment('=' * 60)

    # Pause for incubation
    protocol.pause(
        'INCUBATION PAUSE\n'
        '----------------\n'
        'Transfer plate to incubator for 24 hours.\n'
        'Press RESUME when ready for Fluo-4 calcium imaging.'
    )

    # =========================================================================
    # PROTOCOL STEPS - FLUO-4 ADDITION (after 24h)
    # =========================================================================

    if not skip_fluo4:
        protocol.comment('=' * 60)
        protocol.comment('PHASE 2: FLUO-4 AM CALCIUM DYE ADDITION')
        protocol.comment(f'Fluo-4 volume: {fluo4_vol} µL per well')
        protocol.comment('=' * 60)

        protocol.comment(f'Adding {fluo4_vol} µL Fluo-4 AM to {len(all_treatment_wells)} wells')

        # Add Fluo-4 to all treatment wells
        for well_name in all_treatment_wells:
            p1000.pick_up_tip()
            p1000.aspirate(fluo4_vol, fluo4.bottom(z=2))
            p1000.dispense(fluo4_vol, cell_plate.wells_by_name()[well_name].bottom(z=5))
            p1000.touch_tip()
            p1000.blow_out(cell_plate.wells_by_name()[well_name].top())
            p1000.drop_tip()

        protocol.comment('=' * 60)
        protocol.comment('FLUO-4 ADDITION COMPLETE')
        protocol.comment('=' * 60)
    else:
        protocol.comment('=' * 60)
        protocol.comment('SKIPPING FLUO-4 ADDITION (per parameter setting)')
        protocol.comment('=' * 60)

    protocol.comment('Next steps:')
    protocol.comment('1. Incubate 30 min at 37°C (protected from light)')
    protocol.comment('2. Read on plate reader:')
    protocol.comment('   - Excitation: 494 nm')
    protocol.comment('   - Emission: 516 nm')
    protocol.comment('   - Kinetic read recommended for transient capture')
    protocol.comment('=' * 60)


# =============================================================================
# REAGENT PREPARATION GUIDE
# =============================================================================
"""
## Reagent Preparation Guide

### Stock Solutions
| Reagent | Stock Conc | Volume Needed | Storage | Prep Instructions |
|---------|------------|---------------|---------|-------------------|
| TNF-α | 100 µg/mL | 10 µL | -20°C | Reconstitute in sterile PBS + 0.1% BSA |
| IL-1β | 100 µg/mL | 10 µL | -20°C | Reconstitute in sterile PBS + 0.1% BSA |
| Fluo-4 AM | 1 mM | 20 µL | -20°C | Dissolve in anhydrous DMSO |

### Working Solutions (Prepare Fresh)

**Vehicle Control (10 mL in A1)**
- RPMI 1640 + B27 supplement (or your CM maintenance media)

**TNF-α 10 ng/mL (3 mL in A2)**
- 0.3 µL of 100 µg/mL stock + 3 mL media
- Or 3 µL of 10 µg/mL stock + 3 mL media

**TNF-α 50 ng/mL (3 mL in A3)**
- 1.5 µL of 100 µg/mL stock + 3 mL media
- Or 15 µL of 10 µg/mL stock + 3 mL media

**IL-1β 10 ng/mL (3 mL in A4)**
- 0.3 µL of 100 µg/mL stock + 3 mL media

**IL-1β 50 ng/mL (3 mL in A5)**
- 1.5 µL of 100 µg/mL stock + 3 mL media

**Conditioned Media (3 mL in A6)**
- M1 or M2 macrophage conditioned media
- OR additional media control

**Fluo-4 AM 2 µM Working Solution (8 mL in A12)**
- 16 µL of 1 mM Fluo-4 AM stock
- 8 mL imaging buffer (HBSS + 10 mM HEPES, pH 7.4)
- Add 3.2 µL of 10% Pluronic F-127 (final 0.004%)
- Prepare fresh, protect from light

### Reservoir Layout (nest_12_reservoir_15ml)
| Position | Contents | Volume | Notes |
|----------|----------|--------|-------|
| A1 | Media (vehicle) | 10 mL | Include 2 mL dead volume |
| A2 | TNF-α 10 ng/mL | 3 mL | Warm to 37°C before use |
| A3 | TNF-α 50 ng/mL | 3 mL | Warm to 37°C before use |
| A4 | IL-1β 10 ng/mL | 3 mL | Warm to 37°C before use |
| A5 | IL-1β 50 ng/mL | 3 mL | Warm to 37°C before use |
| A6 | Conditioned media | 3 mL | Warm to 37°C before use |
| A7-A11 | Empty | - | |
| A12 | Fluo-4 AM 2 µM | 8 mL | Keep protected from light |

### Pre-Protocol Checklist
- [ ] Cardiac organoids plated 24-48h prior
- [ ] Cells are attached and beating
- [ ] Cytokine stocks thawed on ice
- [ ] Working solutions prepared fresh
- [ ] Reservoir loaded and on deck
- [ ] 2x tip racks loaded (A1, A2)
- [ ] Trash bin in A3
- [ ] Robot calibrated for plate type

### Estimated Tip Usage
- Treatment addition: ~6-7 tips (one per treatment group)
- Fluo-4 addition: ~72 tips (one per well)
- Total: ~78-79 tips = 1 rack minimum (have 2 for safety)

### Estimated Runtime
- Treatment phase: ~15 minutes
- Incubation: 24 hours (manual)
- Fluo-4 phase: ~30 minutes
- Fluo-4 incubation: 30 minutes (manual)
- Total Opentrons time: ~45 minutes
"""
